### ISSUE TITLE
GBP prices

### ISSUE THREAD

**Issue by zeeraktalat** [afadil/wealthfolio#107]
Hi folks,

First of all, great app. I've noticed a bug in the system. though. The FTSE (and Yahoo finance) lists UK stocks in pence rather than pounds. In the app, however, the price of UK stocks pulled from Yahoo Finance is listed in pounds. An appropriate fix to this, would simply be to divide Yahoo! Finance listings with 100 to get the right price.

**Comment by afadil** [comment]
Fixed in [v1.0.14](https://github.com/afadil/wealthfolio/releases/tag/v1.0.14) 
You can update exchange rate in settings now. Like GBP to GBp rate=100.
