### ISSUE TITLE
Cash Balance Becomes Negative with Multiple `BUY` Activity Orders

### ISSUE THREAD

**Issue by dp-singh** [afadil/wealthfolio#108]
When only BUY orders are input, the cumulative cash balance becomes negative on the AccountPage. (Refer to the screenshot)

Steps to Reproduce:
- Enter multiple BUY orders for share in specific account.
- Observe that the cash balance becomes negative on the AccountPage.

![image](https://github.com/user-attachments/assets/4e1f2b17-3f7b-42a2-a3c4-36d0b589c5a4)
![image](https://github.com/user-attachments/assets/155ceaba-97b1-4be1-bd37-ccf664b0a7e0)

**Technical Observation:**
In the [calculate_historical_value](https://github.com/afadil/wealthfolio/blob/3929a961631eda965fcb61e7c700258885fc6bc1/src-core/src/portfolio/portfolio_service.rs#L364-L490) function, the handling of `cumulative_cash` assumes that there are sufficient "DEPOSIT", "TRANSFER_IN", or "CONVERSION_IN" activities to cover the costs associated with BUY orders.

**Comment by dp-singh** [comment]
Proposed solution
- Ensure there is sufficient cash available before adding  BUY orders activity; if not,  alert the user.
-  Eliminate cumulative_cash tracking and handle cash transactions as separate from portfolio management, treating cash inflows as additional funds.

**Comment by afadil** [comment]
Mybe add an activity type holding to input a quantity and average price without impacting cash-flow

**Comment by afadil** [comment]
You can now use Transfer_in activity type to log holding without impacting cash-flow
