### ISSUE TITLE
[Bug] MacOS app crashes when editing an activity, changing the symbol

### ISSUE THREAD

**Issue by Catali-N** [afadil/wealthfolio#109]
Platform: Macbook M1 Pro, MacOS Sonoma Version 14.6.1 (23G93)
Version: Version 1.0.13 (20240912.210414)

*Steps to reproduce*
1. Go to an activity and enter the edit flow
2. Edit the symbol of activity - my case from ADA-USD to ADA-EUR
3. Tap on 'Update Activity'

The app crashes, the activity is not updated

**Comment by afadil** [comment]
Fixed in [v1.0.14](https://github.com/afadil/wealthfolio/releases/tag/v1.0.14)
