### ISSUE TITLE
manual position day will be set to day - 1

### ISSUE THREAD

**Issue by ya0** [afadil/wealthfolio#110]
i am using the windows `.exe` (1.0.13 x64) from the website. when i manually try to put in a buy position for a date `x.y.2024` (here `x` is for day and `y` is for month) it will be saved for `x-1.y.2024`. when i edit it again i can change the date again to `x.y.2024` but the day will again be set back by one.

**Comment by afadil** [comment]
Duplicate. See #39 
Fix will be shipped in the next version
