### ISSUE TITLE
White screen on 1.0.14

### ISSUE THREAD

**Issue by mikecousins** [afadil/wealthfolio#115]
![image](https://github.com/user-attachments/assets/b85176d3-8949-4211-8cd2-197dfeb124e9)

**Comment by afadil** [comment]
I think first calculation of history data is taking too much time. I’ll have a look. Can you restart the app and see if things get better

**Comment by mikecousins** [comment]
Restarting doesn't help. It also feels like something is jamming up all the network connections as on the activity page the symbol search now never returns either.

**Comment by afadil** [comment]
Ok, thanks for the feedback. Will look closer. This is the problem of testing only on macOS😔.

**Comment by mikecousins** [comment]
![image](https://github.com/user-attachments/assets/b701de61-da60-423f-bde8-2bd734bdf8db)
![image](https://github.com/user-attachments/assets/d12b0c26-db15-4bd7-9b53-d41fee02bae1)

Same behaviour on Mac. Maybe it's related to the activity issues I had before 😢

**Comment by afadil** [comment]
Improved startup time in v1.0.15.
The other problem you have is probably because the app can connect to Yahoo Finance pour symbol search and market data.

**Comment by mikecousins** [comment]
It's working now!
