### ISSUE TITLE
improve manual entry of dividends

### ISSUE THREAD

**Issue by sosonis** [afadil/wealthfolio#118]
The current manual dividends income entry results into the dividend activity appearing as "No of shares" the total dividend amount, multiplied by $1 (unit price) and resulting to the (correct) total dividend amount.

Dividends entered through CSV import, appear in a better way: 1 'share' multiplied by unit price which is the total dividend amount deposited.

**Comment by afadil** [comment]
Fixed in v1.0.16

**Comment by sosonis** [comment]
Thank you!
