### ISSUE TITLE
Package for nix/NixOS

### ISSUE THREAD

**Issue by workflow** [afadil/wealthfolio#119]
Hi, awesome-looking project, can't wait to try it out :)

There's an [effort to build this in nixpkgs](https://github.com/NixOS/nixpkgs/issues/341027) underway that could use some help.

**Comment by kilianar** [comment]
I finally got wealthfolio packaged for nixpkgs in https://github.com/NixOS/nixpkgs/pull/351459. It’s already merged, so it should hit the unstable channels soon. You can keep an eye on the progress here: https://nixpk.gs/pr-tracker.html?pr=351459

**Comment by workflow** [comment]
Amazing! :heart:
