### ISSUE TITLE
Searching for symbol always returns Something went wrong

### ISSUE THREAD

**Issue by fdeus** [afadil/wealthfolio#12]
On adding an activity, searching for symbol always returns "Something went wrong" message.
It is also not clear the format the should be searched for. I tried searching for name and ticker.

Tested on an Intel based mac.

**Comment by rebicul** [comment]
+1 can confirm. Running on a late 2012 Intel Core i7 Mac mini.

![Screenshot 2024-06-15 at 11 05 08 AM](https://github.com/afadil/wealthfolio/assets/7926754/461bce92-af5d-4e34-b4b2-02d66a6d25b6)

**Comment by afadil** [comment]
It looks like the Yahoo Finance API has changed. The app uses the `yahoo_finance_api` Rust library, so I'll need to have a look at it.

**Comment by rebicul** [comment]
Looks like Yahoo Finance has slowly been taking away access: https://youtu.be/NBaZMBL7eTg

>The Yahoo! Finance API is slowly blocking access to its data. So, you my have got the "Will be right back... Thank you for your patience. Our engineers are working quickly to resolve the issue" error when you try to make an API call. Or, you may have gotten the "code": "Unauthorized", "description:", "Invalid Crumb" JSON response.

historic data fetching still works: https://query1.finance.yahoo.com/v8/finance/chart/AAPL?metrics=high?&interval=1d&range=5d

This URL returns data too: https://query1.finance.yahoo.com/v8/finance/chart/AAPL?region=US&lang=en-US&includePrePost=false&interval=2m&useYfid=true&range=1d&corsDomain=finance.yahoo.com&.tsrc=finance
