### ISSUE TITLE
Cannot add fractional shares manually

### ISSUE THREAD

**Issue by maxthraxx** [afadil/wealthfolio#143]
OSX.

If I try to Add Manually in Activity, and enter a non integer number (for fractional shares) under Shares, it says "Enter a valid value".

**Comment by afadil** [comment]
Hey, 
I Can't reproduce this. Can you please provide the app version and screenshot or the value you trying to add.

**Comment by maxthraxx** [comment]
<img width="1440" alt="ss1" src="https://github.com/user-attachments/assets/7f837be9-f414-46c9-b6b9-5bc7a3fda69e">
<img width="1440" alt="ss2" src="https://github.com/user-attachments/assets/ad76381c-ed6e-441f-8eb4-f0c6a20f6e4c">

App version 1.0.20.

**Comment by afadil** [comment]
Can you please test if you still have the issue with v1.0.21?

**Comment by maxthraxx** [comment]
> Can you please test if you still have the issue with v1.0.21?

Tested and now working on v1.0.21, thank you very much!

**Comment by maxthraxx** [comment]
Closing as completed.
