### ISSUE TITLE
Holding list can list up to 50 entries

### ISSUE THREAD

**Issue by sosonis** [afadil/wealthfolio#145]
The Holdings list can list up to 50 entries and the scroll bar will not show the remaining lines (securities are searchable though).
It would also be nice if the window showed the total number of securities, as the activity window respectively, which also lists the first 50 entries, but also displays at the bottom the total number of activities.

**Comment by Yiroh** [comment]
So, you are suggesting adding the total number of activities in the holdings tab?

**Comment by sosonis** [comment]
No I meant that the Holdings window (Holdings >> Holdings pane) should be able to list all securities in an account, if they are more than 50. In the same fashion that activities pane can show all of them, regardless of their number.

Interestingly, in the Accounts page all holding securities are listed, even if they are >50.

**Comment by Yiroh** [comment]
Ah, alright! I shall work on this to have the holdings window have all the securities just like the accounts page. Glad I asked because I thought you wanted a small "Total Securities: #" at the bottom which would not have been helpful in solving your issue.

**Comment by Yiroh** [comment]
It's been a while, but this issue will be fixed in an upcoming version, thanks for the patience and help in clarifying the desired outcome.

**Comment by sosonis** [comment]
Thanks you!
