### ISSUE TITLE
"By Currency" plot not working properly

### ISSUE THREAD

**Issue by rafaelgreca** [afadil/wealthfolio#154]
I have investments in European Euro and Brazilian Reais; currently, my account base currency is set to Euro. However, the "By Currency" plot on the "Holdings" page only shows my portfolio value in Euro (the Brazilian Reais is being converted to Euro and the sum is being displayed). Is this correct? I thought that would display both currencies and that my portfolio value (in Euro) would be displayed on the "Dashboard" page.

I'm running Wealthfolio version 1.0.20 on Ubuntu 24.04.01 LTS.

**Comment by afadil** [comment]
It should display the pie chart by currency. The currency used is the one for the stock symbol. Make sure to use the right symbol in the right market. You can check the currency in the activity page for each transaction.
- The chart should display the cash value in the account currency.
- The investment value in the stock currency.

Can you please provide more details, like an example of the stock/ETF in the Brazilian market?

**Comment by rafaelgreca** [comment]
Oh, ok. I think now I understand what happened. I don't have any stocks or ETFs in the Brazilian market, only in the European market (VWCE). What I have in Brazilian reais is equivalent to an American bond, so I'm adding my gains manually by the end of each month. Do you think it's possible to extend that feature to consider not just stocks or ETFs but any kind of investment in that current currency?

**Comment by afadil** [comment]
How to you add the gain manually? using a dividend/interest activity type?

**Comment by rafaelgreca** [comment]
Yes! I use the "Deposit" option to add the initial value and then use the "Interest Rate" option when I manually add my monthly gains.

**Comment by afadil** [comment]
Added in v1.0.21
You can now disable stock lookup and add a custom symbol
![Screenshot 2024-11-14 at 10 30 32 PM](https://github.com/user-attachments/assets/6678be74-6abc-4c75-9885-1ec371936db0)
