### ISSUE TITLE
Change Shares/Price/Fee Input Placeholders

### ISSUE THREAD

**Issue by wrrnlim** [afadil/wealthfolio#158]
The Shares/Price/Fee inputs have the value "0". This should be a placeholder instead of an actual value. Currently, the user has to delete the "0" value before typing in a value, or else the inputted value will be prepended with a "0" 

![image](https://github.com/user-attachments/assets/98142170-e7c7-4c9e-aa2b-f17534e62a09)

**Comment by afadil** [comment]
Added in v1.0.21
![Screenshot 2024-11-14 at 10 30 32 PM](https://github.com/user-attachments/assets/2358a5cd-69a9-4e7a-8d40-0122d9921e68)
