### ISSUE TITLE
Currency selector for fee and price in manual activity. 

### ISSUE THREAD

**Issue by addedlovely** [afadil/wealthfolio#161]
Is a bit of a European centric issue, but my trading account is in GBP. I have a EUR share to enter an activity for. 

The share price is in EUR, the fee is GBP and the total I paid is in GBP.

When adding an activity manually, I'm assuming the values are in GBP as there is no currency selector ( assuming the currency matches the setting of the trading account ).

But on the 'Activity' listing screen the values are show in EUR.

<img width="1478" alt="Screenshot 2024-11-04 at 22 25 03" src="https://github.com/user-attachments/assets/846e005c-4fd4-458e-9a3a-bf9464d54a22">

Think for my use case would be great to have a currency field for both share price and fee paid.

**Comment by afadil** [comment]
Added in v1.0.21
![Screenshot 2024-11-14 at 10 30 32 PM](https://github.com/user-attachments/assets/29fa7d89-63d8-4783-9164-75c8cb677e3e)
