### ISSUE TITLE
Average stock price as an alternative method to add activities

### ISSUE THREAD

**Issue by gjmveloso** [afadil/wealthfolio#173]
It would be great to have an alternative way to add/import activities, particularly those based on securities.

Some other portfolio tracking applications uses the number of shares (including fractional ones) and the average price per share as an alternative to track portfolio performance.

It’s much simpler than adding time-based transactions (discrete buy and sell movements) as of today.

**Comment by afadil** [comment]
Hello,
This is can be done using transfer In activity type:

![Screenshot 2024-12-14 at 1 28 07 PM](https://github.com/user-attachments/assets/61e8ba4c-ac92-4ef0-ae4f-fe044971dc2a)
