### ISSUE TITLE
Ability to specify the stock for the dividend and automatic dividend information

### ISSUE THREAD

**Issue by WeGoToMars** [afadil/wealthfolio#20]
Hi, and thank you for making this!

Is there a plan to add the ability to specify a stock when manually adding a dividend? It would make keeping track of them easier, and they can be automatically included in the stock's return in the UI.

Yahoo Finance provides data for dividends ([example for AAPL](https://finance.yahoo.com/quote/AAPL/history/?period1=from&period2=to&interval=div%7Csplit&filter=div&frequency=1d&includeAdjustedClose=true)), and yahoo_finance_api supports retrieving this information. Are there plans to add an automatic dividend sync?

**Comment by afadil** [comment]
Added dashboard for dividends and interest in version [v1.0.5](https://github.com/afadil/wealthfolio/releases/tag/v1.0.5).
No current plan to add automatic dividend sync. Maybe later.
