### ISSUE TITLE
Generic error when adding activity

### ISSUE THREAD

**Issue by kylewintaur** [afadil/wealthfolio#22]
Hopefully I'm not just doing something wrong, but when adding any activity, with any stock (ASX:ABB, NASDAQ:TSLA, etc), with any date (past or present), I get "Error adding this activity":

<img width="1237" alt="image" src="https://github.com/user-attachments/assets/aa566786-549b-414b-ab75-395cdb47dc70">

If there's somewhere I can look to find more detailed logs, please let me know

**Comment by HaimW** [comment]
can confirm i am getting this as well.

**Comment by afadil** [comment]
Can you please confirm if you're still experiencing this issue? It works for me. Maybe a temporary issue with Yahoo Stock API.

**Comment by HaimW** [comment]
still the same, any logs i can check?

**Comment by afadil** [comment]
New version released with updated Yahoo stock API library. Can you please confirm if you're still experiencing this issue?

**Comment by HaimW** [comment]
issue resolved. but now i get diff issue. its always shows like the portfolio is down by 100%

**Comment by Wout-Boat** [comment]
Currently experiencing this error message when adding a transaction. Downloaded today.

**Comment by mikecousins** [comment]
Same here.

**Comment by kuciniak1** [comment]
Same for me. I am sometimes able to add transaction without symbol and sometimes not.

**Comment by baldurrensch** [comment]
Same here

**Comment by alexanderameye** [comment]
Same issue, I am not able to add activities/transactions.

**Comment by mocdaniel** [comment]
Same problem, but only with the Homebrew package. When installing the downloaded dmg from the website, it works for me.

**Comment by maximevince** [comment]
Same here, on Arch Linux:
![image](https://github.com/user-attachments/assets/86c526d3-57c5-46c6-89cd-575470077807)

Edit:
upgraded from v1.0.6 to v 1.0.10, still the same issue

**Comment by mikecousins** [comment]
Still the same issue on 1.0.12

**Comment by mikecousins** [comment]
Tested on both Windows and M1 Macbook Pro. Still broken on 1.0.13.
