### ISSUE TITLE
Stock prices are not fetched

### ISSUE THREAD

**Issue by tgdn** [afadil/wealthfolio#36]
<img width="1152" alt="image" src="https://github.com/user-attachments/assets/17863af8-5637-4408-9493-ade4e9dc66de">

**Comment by praserocking** [comment]
+1 same problem. Seems like Yahoo Finance calls are breaking. Site is also not down right now, https://www.isitdownrightnow.com/finance.yahoo.com.html

**Comment by matdehaast** [comment]
Quotes appear to be fetched on load. If I close and open the app it appears to get the data

**Comment by afadil** [comment]
Yes, for now quotes are fetched on load and stored locally. Sometimes Yahoo api are down.

**Comment by tgdn** [comment]
Maybe it would make sense fetching quotes upon adding a new holding? Or adding a "fetch quotes" button?

Right now when I add a holding to my portfolio its value is 0 and my portfolio value is negative.

**Comment by vitorhugoro1** [comment]
@afadil maybe adding a simple alert this could happen and recommend user to close and re-open the app.

**Comment by afadil** [comment]
Quotes are refeched on activity update and app startup. Will add a button soon to trigger this manually.

**Comment by afadil** [comment]
You can now hover the total value in home page, account page and symbol page to display a button that triggers market data fetching.

**Comment by muzzah** [comment]
![image](https://github.com/user-attachments/assets/6f0a002c-c32c-4a70-b42a-0026e60b941d)

Just downloaded the app to try and I am noto seeing any quotes being refreshed at the moment. Latest version.
Whats the URL that is used for these updates?
