### ISSUE TITLE
when adding activity it is inserted with a date of a previous day

### ISSUE THREAD

**Issue by mjazwiecki** [afadil/wealthfolio#39]
I want to record a "BUY" activity for August 15, 2024. But it shows up as the previous day in the activity list. What's going wrong?

**Comment by tkalmi** [comment]
The same is happening to me too. Just a wild guess, but I'm on GMT+3, so perhaps the Activity records the date as `2024-08-15T00:00:00.000+3` but the UI displays it in UTC, i.e., `2024-08-14T21:00:00.000Z`?
