### ISSUE TITLE
Activities - Change quantity and price to decimal

### ISSUE THREAD

**Issue by February30th** [afadil/wealthfolio#41]
The activity quantity and price are coded a f64, this creates an issue with fractional shares.

**Comment by afadil** [comment]
what is the issue with f64? You can log decimal values for quantity and price.

**Comment by February30th** [comment]
Example csv to reproduce decimal issues

```
date,symbol,quantity,activityType,unitPrice,currency,fee
2024-07-05 10:00:43.343,BMW3.DE,0.0481040000,BUY,83.15,EUR,0
2024-07-16 08:20:07.675,BMW3.DE,0.1925370000,BUY,83.1,EUR,0
2024-07-22 10:56:01.155,BMW3.DE,0.2406410000,SELL,84.55,EUR,0
```

**Comment by February30th** [comment]
Also noticed that the sql fields are created as NUMERIC instead of a DECIMAL

**Comment by shivasurya** [comment]
Yeah it would be really good to support decimal to accomodate fractional shares

**Comment by afadil** [comment]
The already support franctional shares. I have no problem importing the CSV example you provided:
![Screenshot 2024-09-07 at 5 58 44 PM](https://github.com/user-attachments/assets/e36ab07f-4ef8-495e-92d2-7808735020a5)

**Comment by February30th** [comment]
Check the holdings tab.

**Comment by araishikeiwai** [comment]
I also have this issue where one of my holdings (fully sold) is still listed as having 4.20692347383774e-16 units left

**Comment by afadil** [comment]
Done in v1.0.18
