### ISSUE TITLE
Feature Request:  CSV Import Profiles

### ISSUE THREAD

**Issue by ssardegna** [afadil/wealthfolio#42]
Each financial institution has its own CSV export format and transactions types.  It would be ideal to a CSV profile that attaches to each account that can be set up once and reused for future imports.  The profile would automatically map the CSV columns to the required import fields and ideally also map the transaction types provided by the institution to the activity types supported in the app.

**Comment by afadil** [comment]
Implemented in v1.0.20.
See docs here: https://wealthfolio.app/docs/guide#csv-import
