### ISSUE TITLE
Feature request: Data export

### ISSUE THREAD

**Issue by blewsky** [afadil/wealthfolio#43]
Great tool! Looks really nice and polished.
Do you plan to implement data export (e.g. csv files) to the software? Without the option to export, the tool is a lot less powerful and it is hard to justify investing a lot of time in ingesting and maintaining all data if there is no way to export the data to e.g. simple csv or Google sheets.

**Comment by afadil** [comment]
Yes, the data are stored locally on an SQLite file. I'm planning to add export db and csv.
You can find db file in ~/Library/Application Support/com.teymz.wealthfolio/app.db

**Comment by afadil** [comment]
Done in v1.0.18
![Export Feature](https://github.com/user-attachments/assets/925c90c6-3595-48ba-a057-29bc34dc3587)
