### ISSUE TITLE
Activity date not respecting selected date

### ISSUE THREAD

**Issue by DVSLabs** [afadil/wealthfolio#52]
When I add or modify a BUY activity and I select the date as 12th of August 2024 and hit update it, the activity will show 11th of August 2024 instead. Time zone on my system is Sydney, Australia if that has anything to do with it. It happens with any date, that's just the example I chose.

https://github.com/user-attachments/assets/4f8ed8ed-a250-45d3-a05f-493cc40733c1

**Comment by alexanderameye** [comment]
See https://github.com/afadil/wealthfolio/issues/39

**Comment by DVSLabs** [comment]
thanks for pointing out the previous issue. closing as duplicate
