### ISSUE TITLE
Non-user-friendly message for invalid activity type

### ISSUE THREAD

**Issue by alexanderameye** [afadil/wealthfolio#67]
The error message for an invalid activity type leaks the underlying enum type. Should ideally be changed to a more user-friendly one?

<img width="576" alt="image" src="https://github.com/user-attachments/assets/57672e83-85cc-4889-8573-d90bac3efe93">

**Comment by afadil** [comment]
Fixed in [v1.0.9](https://github.com/afadil/wealthfolio/releases/tag/v1.0.9)
