### ISSUE TITLE
Cannot add an activity of type Deposit or Withdrawal

### ISSUE THREAD

**Issue by cuicui-V5** [afadil/wealthfolio#73]
When adding an activity, if deposit is selected as the type and an amount is entered, clicking Add Activity does not produce any response.
![Snipaste_2024-09-09_00-27-54](https://github.com/user-attachments/assets/6bb75fa9-b685-43f6-af60-1c883e7c795b)
At this time, switch the type to buy, and find that the price turns red
![Snipaste_2024-09-09_00-28-53](https://github.com/user-attachments/assets/163e9fec-e248-4623-93a3-f3915c1e3645)
Fill in the price, then switch to deposit, then you can submit it correctly

**Comment by afadil** [comment]
Fixed in [v1.0.9](https://github.com/afadil/wealthfolio/releases/tag/v1.0.9)
