### ISSUE TITLE
CSV format documentation

### ISSUE THREAD

**Issue by KevinColemanInc** [afadil/wealthfolio#75]
It isn't clear what the column headers are supposed to be. 

<img width="800" alt="image" src="https://github.com/user-attachments/assets/538ff1b1-ea07-4e4d-9a37-178c53331a66">

The documentation in the top says:

> Columns should include Date, Symbol, Quantity, Activity Type, Unit Price, Currency, and Fee.

When I tried uploading a csv file with the column being `Date`, I get this error:

<img width="762" alt="image" src="https://github.com/user-attachments/assets/73eb97dc-a583-4962-aeae-91ade8245dc4">

The example CSV format says:

> date,symbol,quantity,activityType,unitPrice,currency,fee

Is it `Date` or `date`?

**Comment by afadil** [comment]
Columns headers are in the showed CSV example. Will update the this page to avoid confusion
date,symbol,quantity,activityType,unitPrice,currency,fee

**Comment by KevinColemanInc** [comment]
another feedback, when I was trying to modify the CSV export to match the documentation in this screen, the "How to Import" view disappears when I switch which program is active. This meant, I couldn't see the documentation when had the CSV open in another program to edit the columns.

Could you leave the documentation up when the application is switched?

**Comment by cincauhangus** [comment]
Just a side comment, is there a place you can describe the deposit/withdrawal vs transfer in/out? Especially if these enums does different things in how the graphs and values are shown/calculated.

**Comment by afadil** [comment]
Fixed in [v1.0.11](https://github.com/afadil/wealthfolio/releases/tag/v1.0.11)
