### ISSUE TITLE
Activity dates are incorrect by negative 1 day

### ISSUE THREAD

**Issue by crgeary** [afadil/wealthfolio#77]
Activity dates are being stored with an incorrect date. Dates are incorrect by negative 1 day.

This is most likely because I am based in the UK and currently, BST is 10:50pm and UTC time is 9:50pm. So depending on how you handle & store dates, it's likely subtracting away 1 hour from 00:00 resulting in it being 23:00 the day before, and so it shows as negative 1 day.

In the example below, I choose the 3rd of September, but it get stored as the 2nd of September.

https://github.com/user-attachments/assets/b3fd898d-8743-478c-a589-941faebb22d3

**Comment by alexanderameye** [comment]
See https://github.com/afadil/wealthfolio/issues/39 for duplicate issues

See https://github.com/afadil/wealthfolio/pull/78 for pending fix

**Comment by crgeary** [comment]
Ah sorry! I skimmed the issues and still missed it 🙈 I'll close this. Thanks
