### ISSUE TITLE
Feature: Stock Market Price decimal points settings

### ISSUE THREAD

**Issue by Faaatman** [afadil/wealthfolio#85]
### Issue: 
When the activity is added of type **Buy** the price inserted is in correct decimal points but upon retrieval, the stock itself is retrieved in different decimal points. 
KWD - Kuwaiti Dinars
1 KD has 1000 Fils 
The Stock market operates in Fils so when retrieved its 51.1 fils which is equal to 0.0511 KWD
explanation with Dollars: Dinar = Dollar | Fils = Cents

### Proposal
Set a decimal point settings for each market ex: *.KW

### Example:
Stock: SUKOUK.KW, Price: 0.0511 KWD
What pulled from Yahoo:  SUKOUK.KW, Current Market price : 50.50
What's pulled from Yahoo is correct but it's in Fils and not Dinars I need a way to tell it either in the activity or a place in the settings that any stock *.KW from Kuwaits market to use a different decimal point when retrieving it's current market price

### Activity
![Activity](https://github.com/user-attachments/assets/7b6086d1-7bdb-4edf-b390-7f8c9d038fb7)

### Holding (Total value and all time return jumps since Today's price is in the wrong decimal point)
![Holding](https://github.com/user-attachments/assets/7ac667fd-0e92-4ad8-98f1-f4ae7b57c2b7)

### Yahoo Finance
![Yahoo Finance](https://github.com/user-attachments/assets/a07d8977-f351-4073-8312-b9b7391bb24c)

Thanks for the great project.

**Comment by vpereira** [comment]
It is definitely important too when importing csv using "," as decimal point

**Comment by afadil** [comment]
Looks like the currency of this stock is different from the currency of the account,  

- Stock currency=KWF
- Account currency=KWD

There is no exchange rate between KWD and KWF in Yahoo API.
First time I see this case. I need to dive deep a bit.

**Comment by Faaatman** [comment]
@afadil The issue is similar to [#81](https://github.com/afadil/wealthfolio/issues/81) the ticker in GBp and in the profile its GBP and my issue the ticker is KWF and in the account its KWD.

**Comment by afadil** [comment]
Should be fixed in v1.0.14.
There is now a setting page to update exchange rate manually if can’t be fetched from yahoo finance api. Add Conversion Rate between KWD and KWF
