### ISSUE TITLE
Unable to Manually Add FEE

### ISSUE THREAD

**Issue by tkalmi** [afadil/wealthfolio#91]
Hey there,

I'm trying to manually add a Fee event for a EUR account, but after filling out the form (account, date, and amount) and clicking "Add activity", nothing happens. 
![image](https://github.com/user-attachments/assets/4bdaf50b-1178-4161-9327-2ed20e0a69b3)

I'm on an M1 MacBook Pro running Version 1.0.10 (20240909.220253) of Wealthfolio.

**Comment by afadil** [comment]
Fixed in [v1.0.11](https://github.com/afadil/wealthfolio/releases/tag/v1.0.11)
