### ISSUE TITLE
Update doesn't work

### ISSUE THREAD

**Issue by mikecousins** [afadil/wealthfolio#92]
I get a message saying that there's an update available:
![image](https://github.com/user-attachments/assets/24b927f7-c896-4e84-981f-7d7ac42697e9)

It then gives a GAC prompt which I say yes to and then it installs very quickly and launches again with the same update available message. No errors are thrown.

**Comment by Jgeyen** [comment]
I just ran into a similar issue on Mac Apple Silicon. It said there is an update. Allowed it to update but after it requested to shut down the app, it wouldn't start back up. I uninstalled and installed from the website and it still won't start.

**Comment by sosonis** [comment]
I run into the same issue upgrading from 1.0.10 to 1.0.11. The application does not load anymore. I uninstalled it and reinstall it and it still does not work.
I reverted back to 1.0.10 version.

**Comment by afadil** [comment]
@maidh91 I think the refactoring you did broke the database URL. The database should be in the data_dir, not the current_dir. Any idea how to get this URL without using Tauri (which is not in src-core anymore)?
I'll remove the 1.0.11 for now, until we find a fix

**Comment by afadil** [comment]
Should be fixed in v1.1.12. Can you please confirm?

**Comment by mikecousins** [comment]
Works a bit better with 1.0.12. Here's how it went for me:
- launched and got a 1.0.6 to 1.0.12 upgrade modal
- did the install and it seemed like it actually ran
- app started up and gave me the upgrade modal again saying i was still on 1.0.6
- ignored the upgrade modal
- closed the app
- started the app
- no upgrade modal this time

**Comment by sosonis** [comment]
> Should be fixed in v1.1.12. Can you please confirm?

It works now. Only minor issue that I noticed is that it takes a while (8-10 secs on my M1 Max system) for the data to appear when you start the app.
The same delay happens when you right click and choose reload on the Dashboard pane.

**Comment by afadil** [comment]
Closing this. History calculation are now persisted to database starting v1.014. This  should improve performance after first calculation.
