### ISSUE TITLE
Feature request: Deposit crypto like cash

### ISSUE THREAD

**Issue by surfaceflinger** [afadil/wealthfolio#97]
Hi,

Please consider making an option to deposit crypto instead of buy/sell. Makes more sense in case of eg. receiving donations.
I'm not a trader and I would prefer to pick just eg. `XMR` and input how much I have/got in total instead of `XMR/USD` and then also checking for how much 1 XMR goes rn

delta.app already allows for that and I would love to replace it with Wealthfolio :)

**Comment by afadil** [comment]
Related to #108. I think we can add an activity type holding to log a quantity and average price without impacting cash-flow

**Comment by afadil** [comment]
You can now (starting 1.0.18) use TRANSFER_IN/ TRANSFER_OUT to log  a holding without impaction cashflow.

**Comment by surfaceflinger** [comment]
yippee, ill check it out, thanks!

**Comment by surfaceflinger** [comment]
exactly what I wanted, thank you!
